name: CI
on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Checkout code
        id: checkout
        uses: actions/checkout@v6

      - name: âœ¨ Markdownlint CLi2 Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: DavidAnson/markdownlint-cli2-action@v21
        with:
          globs: "**/*.md"
          config: .markdownlint-cli2.jsonc

      - name: âœ¨ Prettier Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --config .prettierrc --check .
          dry: true

      - name: âœ¨ PSScriptAnalyzer Action
        if: steps.checkout.outcome == 'success' && !cancelled()
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./src/Kari # module root
          recurse: true
          settings: ./PSScriptAnalyzerSettings.psd1
          enableExit: true

  test:
    # TODO - Setup matrix for PS5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    steps:
      - name: âš™ï¸ Checkout code
        uses: actions/checkout@v6

      - name: ğŸŒŒ Get Run Metadata
        id: setup-meta
        uses: ./.github/actions/get-metadata

      - name: ğŸ¥“ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: requirements.psd1

      - name: ğŸ¥“ Cache PowerShell modules
        uses: actions/cache@v4
        with:
          path: $HOME/.local/share/powershell/Modules
          key: ${{ runner.os }}-pwsh-${{ hashFiles('**/requirements.psd1') }}
          restore-keys: |
            ${{ runner.os }}-pwsh-

      - name: ğŸ”» Bootstrap
        run: ./scripts/bootstrap.ps1

      - name: ğŸ§ª Run Pester
        id: tests
        run: Invoke-PSake Test-CI -NoLogo

      - name: ğŸ¥¨ Upload coverage report
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: code-coverage_${{ runner.os }}-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: coverage.xml

      - name: ğŸ¥¨ Upload test results
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: actions/upload-artifact@v5
        with:
          name: test-results_${{ runner.os }}-${{ steps.setup-meta.outputs.short-sha }}-${{ steps.setup-meta.outputs.timestamp }}
          path: testResults.xml

      - name: ğŸ“œ Coverage Report to Codecov
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          fail_ci_if_error: true
          flags: pester
          disable_telem: true

      - name: ğŸ“œ Test Results to Codecov
        if: steps.tests.outcome != 'skipped' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          fail_ci_if_error: true
          flags: pester
          disable_telem: true
